<?php

namespace BlogBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllQuery() : QueryBuilder
    {
        $query = $this->getEntityManager()->createQueryBuilder();

        $query->select('b');
        $query->from('BlogBundle:Blog', 'b');

        return $query;
    }

}
