easy_admin:
    entities:
        User:
            class: AppBundle\Entity\User
            form:
              fields:
                  - username
                  - email
                  - enabled
                  # if administrators are allowed to edit users' passwords and roles, add this:
                  - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                  - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
            label: 'Usuarios'
            list:
                title: "Listado de usuarios"
                max_results: 30
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin